In [167]:
import pandas as pd

各大學深耕計畫經費表：

In [168]:
df = pd.read_csv('University Fund.csv')
df

                                               Number        Name     Fund
0                                              Number        Name     Fund
1                                                0001      國立政治大學   28,579
2                                                0002      國立清華大學  100,000
3                                                0003      國立臺灣大學  180,000
4                                                0004    國立臺灣師範大學   20,690
5                                                0005      國立成功大學  110,000
6                                                0006      國立中興大學   35,202
7                                                0007      國立交通大學  100,000
8                                                0008      國立中央大學   41,546
9                                                0009      國立中山大學   25,303
10                                               0012    國立臺灣海洋大學   13,529
11                                               0013      國立中正大學   16,391
12                                               0014    國立高雄師範大學    4,074
13                                               0015    國立彰化師範大學    5,816
14                                               0016      國立陽明大學   34,190
15                                               0017      國立臺北大學    7,805
16                                               0018      國立嘉義大學    5,745
17                                               0019      國立高雄大學    4,519
18                                               0020      國立東華大學    5,163
19                                               0021    國立暨南國際大學    7,179
20                                               0028    國立臺北藝術大學    4,818
21                                               0029    國立臺灣藝術大學    3,188
22                                               0030      國立臺東大學    5,007
23                                               0031      國立宜蘭大學    5,424
24                                               0032      國立聯合大學    4,476
25                                               0035    國立臺南藝術大學    1,361
26                                               0036      國立臺南大學    4,596
27                                               0037    國立臺北教育大學    5,202
28                                               0039    國立臺中教育大學    4,547
29                                               0044      國立體育大學    3,996
30                                               0048      國立金門大學    3,435
31                                               0049  國立臺灣體育運動大學    3,019
32                                               0052      國立屏東大學    6,774
33                                               1001        東海大學   12,358
34                                               1002        輔仁大學    8,290
35                                               1003        東吳大學    8,968
36                                               1004        中原大學   13,558
37                                               1005        淡江大學    8,907
38                                               1006      中國文化大學    7,231
39                                               1007        逢甲大學   14,820
40                                               學校代碼        學校名稱     核定經費
41                                               1008        靜宜大學    8,672
42                                               1009        長庚大學   16,914
43                                               1010        元智大學    8,377
44                                               1011        中華大學    4,732
45                                               1012        大葉大學    6,964
46                                               1013        華梵大學    2,887
47                                               1014        義守大學    6,854
48                                               1015        世新大學    6,016
49                                               1016        銘傳大學    7,368
50                                               1017        實踐大學    6,632
51                                               1019      高雄醫學大學   10,052
52                                               1020        南華大學    6,012
53                                               1021        真理大學    2,154
54                                               1022        大同大學    3,920
55                                               1027        慈濟大學    5,375
56                                               1028      臺北醫學大學   26,740
57                                               1029      中山醫學大學    5,874
58                                               1033        長榮大學    5,397
59                                               1035      中國醫藥大學   20,226
60                                               1039        玄奘大學    3,917
61                                               1048        亞洲大學    6,370
62                                               1049        開南大學    1,871
63                                               1050        佛光大學    4,842
64                                               1058        明道大學    1,668
65                                               1067      台灣首府大學    1,114
66                                               1079        康寧大學    1,583
67                                               1125    中信金融管理學院      889
68                                               1176   稻江科技暨管理學院      202
69                                               1195       馬偕醫學院    4,306
70                                               1196      法鼓文理學院      381
71                                               1R04     一貫道天皇學院      517
72                                               3002      臺北市立大學    4,440
73  【備註】\n1. 學校排序依教育部統計處學校代碼排序呈現。\n2. 以上含深耕計畫第一部分(...         NaN      NaN

In [169]:
df_fund = df.groupby(['Name'])['Fund'].sum().reset_index()
df_fund

          Name     Fund
0         Name     Fund
1      一貫道天皇學院      517
2         世新大學    6,016
3     中信金融管理學院      889
4         中原大學   13,558
5       中國文化大學    7,231
6       中國醫藥大學   20,226
7       中山醫學大學    5,874
8         中華大學    4,732
9         亞洲大學    6,370
10        佛光大學    4,842
11        元智大學    8,377
12        南華大學    6,012
13      台灣首府大學    1,114
14      國立中央大學   41,546
15      國立中山大學   25,303
16      國立中正大學   16,391
17      國立中興大學   35,202
18      國立交通大學  100,000
19      國立嘉義大學    5,745
20      國立宜蘭大學    5,424
21      國立屏東大學    6,774
22    國立彰化師範大學    5,816
23      國立成功大學  110,000
24      國立政治大學   28,579
25    國立暨南國際大學    7,179
26      國立東華大學    5,163
27      國立清華大學  100,000
28      國立聯合大學    4,476
29    國立臺中教育大學    4,547
30      國立臺北大學    7,805
31    國立臺北教育大學    5,202
32    國立臺北藝術大學    4,818
33      國立臺南大學    4,596
34    國立臺南藝術大學    1,361
35      國立臺東大學    5,007
36      國立臺灣大學  180,000
37    國立臺灣師範大學   20,690
38    國立臺灣海洋大學   13,529
39    國立臺灣藝術大學    3,188
40  國立臺灣體育運動大學    3,019
41      國立金門大學    3,435
42      國立陽明大學   34,190
43      國立體育大學    3,996
44      國立高雄大學    4,519
45    國立高雄師範大學    4,074
46        大同大學    3,920
47        大葉大學    6,964
48        學校名稱     核定經費
49        實踐大學    6,632
50        康寧大學    1,583
51        慈濟大學    5,375
52        明道大學    1,668
53        東吳大學    8,968
54        東海大學   12,358
55      法鼓文理學院      381
56        淡江大學    8,907
57        玄奘大學    3,917
58        真理大學    2,154
59   稻江科技暨管理學院      202
60        義守大學    6,854
61      臺北市立大學    4,440
62      臺北醫學大學   26,740
63        華梵大學    2,887
64        輔仁大學    8,290
65        逢甲大學   14,820
66        銘傳大學    7,368
67        長庚大學   16,914
68        長榮大學    5,397
69        開南大學    1,871
70        靜宜大學    8,672
71       馬偕醫學院    4,306
72      高雄醫學大學   10,052

2019台灣大學排名(前50)：

In [170]:
df_rank = pd.read_csv('50 University Rank.csv')
df_rank

    Rank      Name      總分  A.學術成就  B.教學環境  C.國際化程度  D.產學績效
0      1    國立臺灣大學  100.00  100.00  100.00   100.00  100.00
1      2    國立清華大學   67.63   64.14   59.49    84.43   77.98
2      3    國立成功大學   67.03   59.69   66.65    77.24   74.84
3      4    國立交通大學   65.55   54.92   62.16    87.87   75.95
4      5  國立臺灣師範大學   60.90   55.28   56.36    80.56   64.95
5      6    臺北醫學大學   59.54   51.59   59.22    77.87   60.54
6      7    國立政治大學   59.29   52.43   53.99    95.12   51.82
7      8    國立陽明大學   58.02   59.87   54.47    62.00   58.04
8      9    國立中山大學   56.78   50.63   51.86    76.77   62.64
9     10    國立中興大學   56.76   47.82   56.88    69.87   64.22
10    11    國立中央大學   56.61   53.74   54.77    60.39   63.83
11    12      長庚大學   56.47   56.02   55.96    62.69   52.53
12    13    中國醫藥大學   55.91   53.97   55.96    65.79   50.45
13    14  國立臺灣科技大學   55.51   47.42   50.13    80.00   62.45
14    15  國立臺北科技大學   54.02   46.64   52.62    67.62   60.89
15    16    高雄醫學大學   53.52   49.56   53.43    65.86   50.66
16    17      元智大學   49.75   44.99   44.89    73.91   48.02
17    18      淡江大學   48.18   27.49   48.40    97.09   47.03
18    19      世新大學   48.08   43.73   44.97    70.62   42.96
19    20      逢甲大學   46.53   25.79   49.93    86.63   46.90
20    21      輔仁大學   45.98   29.40   49.67    79.06   43.00
21    22    國立中正大學   45.74   49.50   29.31    64.68   56.36
22    23      東海大學   45.26   26.21   48.91    79.99   46.46
23    24  國立高雄科技大學   45.19   25.35   49.24    64.14   63.12
24    25  國立臺灣海洋大學   44.80   25.67   49.42    66.58   56.91
25    26      中原大學   44.74   26.11   48.45    74.46   49.84
26    27    國立臺北大學   44.63   29.49   47.96    67.08   49.74
27    28      亞洲大學   44.27   48.38   26.45    76.93   43.58
28    29    中國文化大學   44.26   26.48   43.76    78.58   52.59
29    30  國立雲林科技大學   43.72   44.60   27.73    66.14   56.57
30    31      銘傳大學   43.64   26.64   44.49    79.11   45.86
31    32  國立彰化師範大學   43.55   26.42   48.91    60.97   53.58
32    33  國立屏東科技大學   43.49   24.84   46.38    66.61   57.15
33    34      東吳大學   43.34   27.89   47.47    73.46   39.66
34    35  國立臺中教育大學   42.41   45.87   28.48    61.10   48.14
35    36      實踐大學   42.22   25.27   44.31    79.61   39.48
36    37  國立臺北商業大學   41.00   23.08   47.38    59.50   49.45
37    38  國立臺北教育大學   40.93   25.51   47.93    53.29   48.19
38    39    明新科技大學   38.61   21.96   44.02    61.58   41.86
39    40      真理大學   38.19   23.94   43.66    58.20   38.62
40    41  國立虎尾科技大學   38.13   41.98   24.84    46.09   52.19
41    43    國立東華大學   37.04   27.75   28.03    61.66   55.10
42    44      慈濟大學   36.80   27.04   31.48    64.59   44.16
43    45    臺北市立大學   36.41   27.36   29.03    62.61   48.56
44    46      中華大學   36.00   23.32   25.97    78.64   46.39
45    47      義守大學   35.88   24.40   25.62    74.40   48.09
46    48      靜宜大學   35.73   25.20   24.13    80.76   42.31
47    49    國立宜蘭大學   35.72   24.64   28.32    64.13   50.42
48    50    國立高雄大學   35.58   24.27   27.30    67.45   49.43

In [171]:
frames = [df_fund, df_rank]
result = pd.concat(frames)
result

          Name     Fund  Rank      總分  A.學術成就  B.教學環境  C.國際化程度  D.產學績效
0         Name     Fund   NaN     NaN     NaN     NaN      NaN     NaN
1      一貫道天皇學院      517   NaN     NaN     NaN     NaN      NaN     NaN
2         世新大學    6,016   NaN     NaN     NaN     NaN      NaN     NaN
3     中信金融管理學院      889   NaN     NaN     NaN     NaN      NaN     NaN
4         中原大學   13,558   NaN     NaN     NaN     NaN      NaN     NaN
5       中國文化大學    7,231   NaN     NaN     NaN     NaN      NaN     NaN
6       中國醫藥大學   20,226   NaN     NaN     NaN     NaN      NaN     NaN
7       中山醫學大學    5,874   NaN     NaN     NaN     NaN      NaN     NaN
8         中華大學    4,732   NaN     NaN     NaN     NaN      NaN     NaN
9         亞洲大學    6,370   NaN     NaN     NaN     NaN      NaN     NaN
10        佛光大學    4,842   NaN     NaN     NaN     NaN      NaN     NaN
11        元智大學    8,377   NaN     NaN     NaN     NaN      NaN     NaN
12        南華大學    6,012   NaN     NaN     NaN     NaN      NaN     NaN
13      台灣首府大學    1,114   NaN     NaN     NaN     NaN      NaN     NaN
14      國立中央大學   41,546   NaN     NaN     NaN     NaN      NaN     NaN
15      國立中山大學   25,303   NaN     NaN     NaN     NaN      NaN     NaN
16      國立中正大學   16,391   NaN     NaN     NaN     NaN      NaN     NaN
17      國立中興大學   35,202   NaN     NaN     NaN     NaN      NaN     NaN
18      國立交通大學  100,000   NaN     NaN     NaN     NaN      NaN     NaN
19      國立嘉義大學    5,745   NaN     NaN     NaN     NaN      NaN     NaN
20      國立宜蘭大學    5,424   NaN     NaN     NaN     NaN      NaN     NaN
21      國立屏東大學    6,774   NaN     NaN     NaN     NaN      NaN     NaN
22    國立彰化師範大學    5,816   NaN     NaN     NaN     NaN      NaN     NaN
23      國立成功大學  110,000   NaN     NaN     NaN     NaN      NaN     NaN
24      國立政治大學   28,579   NaN     NaN     NaN     NaN      NaN     NaN
25    國立暨南國際大學    7,179   NaN     NaN     NaN     NaN      NaN     NaN
26      國立東華大學    5,163   NaN     NaN     NaN     NaN      NaN     NaN
27      國立清華大學  100,000   NaN     NaN     NaN     NaN      NaN     NaN
28      國立聯合大學    4,476   NaN     NaN     NaN     NaN      NaN     NaN
29    國立臺中教育大學    4,547   NaN     NaN     NaN     NaN      NaN     NaN
30      國立臺北大學    7,805   NaN     NaN     NaN     NaN      NaN     NaN
31    國立臺北教育大學    5,202   NaN     NaN     NaN     NaN      NaN     NaN
32    國立臺北藝術大學    4,818   NaN     NaN     NaN     NaN      NaN     NaN
33      國立臺南大學    4,596   NaN     NaN     NaN     NaN      NaN     NaN
34    國立臺南藝術大學    1,361   NaN     NaN     NaN     NaN      NaN     NaN
35      國立臺東大學    5,007   NaN     NaN     NaN     NaN      NaN     NaN
36      國立臺灣大學  180,000   NaN     NaN     NaN     NaN      NaN     NaN
37    國立臺灣師範大學   20,690   NaN     NaN     NaN     NaN      NaN     NaN
38    國立臺灣海洋大學   13,529   NaN     NaN     NaN     NaN      NaN     NaN
39    國立臺灣藝術大學    3,188   NaN     NaN     NaN     NaN      NaN     NaN
40  國立臺灣體育運動大學    3,019   NaN     NaN     NaN     NaN      NaN     NaN
41      國立金門大學    3,435   NaN     NaN     NaN     NaN      NaN     NaN
42      國立陽明大學   34,190   NaN     NaN     NaN     NaN      NaN     NaN
43      國立體育大學    3,996   NaN     NaN     NaN     NaN      NaN     NaN
44      國立高雄大學    4,519   NaN     NaN     NaN     NaN      NaN     NaN
45    國立高雄師範大學    4,074   NaN     NaN     NaN     NaN      NaN     NaN
46        大同大學    3,920   NaN     NaN     NaN     NaN      NaN     NaN
47        大葉大學    6,964   NaN     NaN     NaN     NaN      NaN     NaN
48        學校名稱     核定經費   NaN     NaN     NaN     NaN      NaN     NaN
49        實踐大學    6,632   NaN     NaN     NaN     NaN      NaN     NaN
50        康寧大學    1,583   NaN     NaN     NaN     NaN      NaN     NaN
51        慈濟大學    5,375   NaN     NaN     NaN     NaN      NaN     NaN
52        明道大學    1,668   NaN     NaN     NaN     NaN      NaN     NaN
53        東吳大學    8,968   NaN     NaN     NaN     NaN      NaN     NaN
54        東海大學   12,358   NaN     NaN     NaN     NaN      NaN     NaN
55      法鼓文理學院      381   NaN     NaN     NaN     NaN      NaN     NaN
56        淡江大學    8,907   NaN     NaN     NaN     NaN      NaN     NaN
57        玄奘大學    3,917   NaN     NaN     NaN     NaN      NaN     NaN
58        真理大學    2,154   NaN     NaN     NaN     NaN      NaN     NaN
59   稻江科技暨管理學院      202   NaN     NaN     NaN     NaN      NaN     NaN
60        義守大學    6,854   NaN     NaN     NaN     NaN      NaN     NaN
61      臺北市立大學    4,440   NaN     NaN     NaN     NaN      NaN     NaN
62      臺北醫學大學   26,740   NaN     NaN     NaN     NaN      NaN     NaN
63        華梵大學    2,887   NaN     NaN     NaN     NaN      NaN     NaN
64        輔仁大學    8,290   NaN     NaN     NaN     NaN      NaN     NaN
65        逢甲大學   14,820   NaN     NaN     NaN     NaN      NaN     NaN
66        銘傳大學    7,368   NaN     NaN     NaN     NaN      NaN     NaN
67        長庚大學   16,914   NaN     NaN     NaN     NaN      NaN     NaN
68        長榮大學    5,397   NaN     NaN     NaN     NaN      NaN     NaN
69        開南大學    1,871   NaN     NaN     NaN     NaN      NaN     NaN
70        靜宜大學    8,672   NaN     NaN     NaN     NaN      NaN     NaN
71       馬偕醫學院    4,306   NaN     NaN     NaN     NaN      NaN     NaN
72      高雄醫學大學   10,052   NaN     NaN     NaN     NaN      NaN     NaN
0       國立臺灣大學      NaN   1.0  100.00  100.00  100.00   100.00  100.00
1       國立清華大學      NaN   2.0   67.63   64.14   59.49    84.43   77.98
2       國立成功大學      NaN   3.0   67.03   59.69   66.65    77.24   74.84
3       國立交通大學      NaN   4.0   65.55   54.92   62.16    87.87   75.95
4     國立臺灣師範大學      NaN   5.0   60.90   55.28   56.36    80.56   64.95
5       臺北醫學大學      NaN   6.0   59.54   51.59   59.22    77.87   60.54
6       國立政治大學      NaN   7.0   59.29   52.43   53.99    95.12   51.82
7       國立陽明大學      NaN   8.0   58.02   59.87   54.47    62.00   58.04
8       國立中山大學      NaN   9.0   56.78   50.63   51.86    76.77   62.64
9       國立中興大學      NaN  10.0   56.76   47.82   56.88    69.87   64.22
10      國立中央大學      NaN  11.0   56.61   53.74   54.77    60.39   63.83
11        長庚大學      NaN  12.0   56.47   56.02   55.96    62.69   52.53
12      中國醫藥大學      NaN  13.0   55.91   53.97   55.96    65.79   50.45
13    國立臺灣科技大學      NaN  14.0   55.51   47.42   50.13    80.00   62.45
14    國立臺北科技大學      NaN  15.0   54.02   46.64   52.62    67.62   60.89
15      高雄醫學大學      NaN  16.0   53.52   49.56   53.43    65.86   50.66
16        元智大學      NaN  17.0   49.75   44.99   44.89    73.91   48.02
17        淡江大學      NaN  18.0   48.18   27.49   48.40    97.09   47.03
18        世新大學      NaN  19.0   48.08   43.73   44.97    70.62   42.96
19        逢甲大學      NaN  20.0   46.53   25.79   49.93    86.63   46.90
20        輔仁大學      NaN  21.0   45.98   29.40   49.67    79.06   43.00
21      國立中正大學      NaN  22.0   45.74   49.50   29.31    64.68   56.36
22        東海大學      NaN  23.0   45.26   26.21   48.91    79.99   46.46
23    國立高雄科技大學      NaN  24.0   45.19   25.35   49.24    64.14   63.12
24    國立臺灣海洋大學      NaN  25.0   44.80   25.67   49.42    66.58   56.91
25        中原大學      NaN  26.0   44.74   26.11   48.45    74.46   49.84
26      國立臺北大學      NaN  27.0   44.63   29.49   47.96    67.08   49.74
27        亞洲大學      NaN  28.0   44.27   48.38   26.45    76.93   43.58
28      中國文化大學      NaN  29.0   44.26   26.48   43.76    78.58   52.59
29    國立雲林科技大學      NaN  30.0   43.72   44.60   27.73    66.14   56.57
30        銘傳大學      NaN  31.0   43.64   26.64   44.49    79.11   45.86
31    國立彰化師範大學      NaN  32.0   43.55   26.42   48.91    60.97   53.58
32    國立屏東科技大學      NaN  33.0   43.49   24.84   46.38    66.61   57.15
33        東吳大學      NaN  34.0   43.34   27.89   47.47    73.46   39.66
34    國立臺中教育大學      NaN  35.0   42.41   45.87   28.48    61.10   48.14
35        實踐大學      NaN  36.0   42.22   25.27   44.31    79.61   39.48
36    國立臺北商業大學      NaN  37.0   41.00   23.08   47.38    59.50   49.45
37    國立臺北教育大學      NaN  38.0   40.93   25.51   47.93    53.29   48.19
38      明新科技大學      NaN  39.0   38.61   21.96   44.02    61.58   41.86
39        真理大學      NaN  40.0   38.19   23.94   43.66    58.20   38.62
40    國立虎尾科技大學      NaN  41.0   38.13   41.98   24.84    46.09   52.19
41      國立東華大學      NaN  43.0   37.04   27.75   28.03    61.66   55.10
42        慈濟大學      NaN  44.0   36.80   27.04   31.48    64.59   44.16
43      臺北市立大學      NaN  45.0   36.41   27.36   29.03    62.61   48.56
44        中華大學      NaN  46.0   36.00   23.32   25.97    78.64   46.39
45        義守大學      NaN  47.0   35.88   24.40   25.62    74.40   48.09
46        靜宜大學      NaN  48.0   35.73   25.20   24.13    80.76   42.31
47      國立宜蘭大學      NaN  49.0   35.72   24.64   28.32    64.13   50.42
48      國立高雄大學      NaN  50.0   35.58   24.27   27.30    67.45   49.43

重新排序

In [172]:
import pandas as pd

# 設置顯示選項
pd.set_option('display.max_rows', None)  # 顯示所有行
pd.set_option('display.max_columns', None)  # 顯示所有列

# 創建DataFrame（假設名為df）
df = pd.DataFrame({'A': range(1, 100), 'B': range(101, 200)})

# 顯示完整表格
data

           Name     Fund  Rank      總分  A.學術成就  B.教學環境  C.國際化程度  D.產學績效
0          Name     Fund   NaN     NaN     NaN     NaN      NaN     NaN
1       一貫道天皇學院      517   NaN     NaN     NaN     NaN      NaN     NaN
2          世新大學    6,016   NaN     NaN     NaN     NaN      NaN     NaN
3      中信金融管理學院      889   NaN     NaN     NaN     NaN      NaN     NaN
4          中原大學   13,558   NaN     NaN     NaN     NaN      NaN     NaN
5        中國文化大學    7,231   NaN     NaN     NaN     NaN      NaN     NaN
6        中國醫藥大學   20,226   NaN     NaN     NaN     NaN      NaN     NaN
7        中山醫學大學    5,874   NaN     NaN     NaN     NaN      NaN     NaN
8          中華大學    4,732   NaN     NaN     NaN     NaN      NaN     NaN
9          亞洲大學    6,370   NaN     NaN     NaN     NaN      NaN     NaN
10         佛光大學    4,842   NaN     NaN     NaN     NaN      NaN     NaN
11         元智大學    8,377   NaN     NaN     NaN     NaN      NaN     NaN
12         南華大學    6,012   NaN     NaN     NaN     NaN      NaN     NaN
13       台灣首府大學    1,114   NaN     NaN     NaN     NaN      NaN     NaN
14       國立中央大學   41,546   NaN     NaN     NaN     NaN      NaN     NaN
15       國立中山大學   25,303   NaN     NaN     NaN     NaN      NaN     NaN
16       國立中正大學   16,391   NaN     NaN     NaN     NaN      NaN     NaN
17       國立中興大學   35,202   NaN     NaN     NaN     NaN      NaN     NaN
18       國立交通大學  100,000   NaN     NaN     NaN     NaN      NaN     NaN
19       國立嘉義大學    5,745   NaN     NaN     NaN     NaN      NaN     NaN
20       國立宜蘭大學    5,424   NaN     NaN     NaN     NaN      NaN     NaN
21       國立屏東大學    6,774   NaN     NaN     NaN     NaN      NaN     NaN
22     國立彰化師範大學    5,816   NaN     NaN     NaN     NaN      NaN     NaN
23       國立成功大學  110,000   NaN     NaN     NaN     NaN      NaN     NaN
24       國立政治大學   28,579   NaN     NaN     NaN     NaN      NaN     NaN
25     國立暨南國際大學    7,179   NaN     NaN     NaN     NaN      NaN     NaN
26       國立東華大學    5,163   NaN     NaN     NaN     NaN      NaN     NaN
27       國立清華大學  100,000   NaN     NaN     NaN     NaN      NaN     NaN
28       國立聯合大學    4,476   NaN     NaN     NaN     NaN      NaN     NaN
29     國立臺中教育大學    4,547   NaN     NaN     NaN     NaN      NaN     NaN
30       國立臺北大學    7,805   NaN     NaN     NaN     NaN      NaN     NaN
31     國立臺北教育大學    5,202   NaN     NaN     NaN     NaN      NaN     NaN
32     國立臺北藝術大學    4,818   NaN     NaN     NaN     NaN      NaN     NaN
33       國立臺南大學    4,596   NaN     NaN     NaN     NaN      NaN     NaN
34     國立臺南藝術大學    1,361   NaN     NaN     NaN     NaN      NaN     NaN
35       國立臺東大學    5,007   NaN     NaN     NaN     NaN      NaN     NaN
36       國立臺灣大學  180,000   NaN     NaN     NaN     NaN      NaN     NaN
37     國立臺灣師範大學   20,690   NaN     NaN     NaN     NaN      NaN     NaN
38     國立臺灣海洋大學   13,529   NaN     NaN     NaN     NaN      NaN     NaN
39     國立臺灣藝術大學    3,188   NaN     NaN     NaN     NaN      NaN     NaN
40   國立臺灣體育運動大學    3,019   NaN     NaN     NaN     NaN      NaN     NaN
41       國立金門大學    3,435   NaN     NaN     NaN     NaN      NaN     NaN
42       國立陽明大學   34,190   NaN     NaN     NaN     NaN      NaN     NaN
43       國立體育大學    3,996   NaN     NaN     NaN     NaN      NaN     NaN
44       國立高雄大學    4,519   NaN     NaN     NaN     NaN      NaN     NaN
45     國立高雄師範大學    4,074   NaN     NaN     NaN     NaN      NaN     NaN
46         大同大學    3,920   NaN     NaN     NaN     NaN      NaN     NaN
47         大葉大學    6,964   NaN     NaN     NaN     NaN      NaN     NaN
48         學校名稱     核定經費   NaN     NaN     NaN     NaN      NaN     NaN
49         實踐大學    6,632   NaN     NaN     NaN     NaN      NaN     NaN
50         康寧大學    1,583   NaN     NaN     NaN     NaN      NaN     NaN
51         慈濟大學    5,375   NaN     NaN     NaN     NaN      NaN     NaN
52         明道大學    1,668   NaN     NaN     NaN     NaN      NaN     NaN
53         東吳大學    8,968   NaN     NaN     NaN     NaN      NaN     NaN
54         東海大學   12,358   NaN     NaN     NaN     NaN      NaN     NaN
55       法鼓文理學院      381   NaN     NaN     NaN     NaN      NaN     NaN
56         淡江大學    8,907   NaN     NaN     NaN     NaN      NaN     NaN
57         玄奘大學    3,917   NaN     NaN     NaN     NaN      NaN     NaN
58         真理大學    2,154   NaN     NaN     NaN     NaN      NaN     NaN
59    稻江科技暨管理學院      202   NaN     NaN     NaN     NaN      NaN     NaN
60         義守大學    6,854   NaN     NaN     NaN     NaN      NaN     NaN
61       臺北市立大學    4,440   NaN     NaN     NaN     NaN      NaN     NaN
62       臺北醫學大學   26,740   NaN     NaN     NaN     NaN      NaN     NaN
63         華梵大學    2,887   NaN     NaN     NaN     NaN      NaN     NaN
64         輔仁大學    8,290   NaN     NaN     NaN     NaN      NaN     NaN
65         逢甲大學   14,820   NaN     NaN     NaN     NaN      NaN     NaN
66         銘傳大學    7,368   NaN     NaN     NaN     NaN      NaN     NaN
67         長庚大學   16,914   NaN     NaN     NaN     NaN      NaN     NaN
68         長榮大學    5,397   NaN     NaN     NaN     NaN      NaN     NaN
69         開南大學    1,871   NaN     NaN     NaN     NaN      NaN     NaN
70         靜宜大學    8,672   NaN     NaN     NaN     NaN      NaN     NaN
71        馬偕醫學院    4,306   NaN     NaN     NaN     NaN      NaN     NaN
72       高雄醫學大學   10,052   NaN     NaN     NaN     NaN      NaN     NaN
73       國立臺灣大學      NaN   1.0  100.00  100.00  100.00   100.00  100.00
74       國立清華大學      NaN   2.0   67.63   64.14   59.49    84.43   77.98
75       國立成功大學      NaN   3.0   67.03   59.69   66.65    77.24   74.84
76       國立交通大學      NaN   4.0   65.55   54.92   62.16    87.87   75.95
77     國立臺灣師範大學      NaN   5.0   60.90   55.28   56.36    80.56   64.95
78       臺北醫學大學      NaN   6.0   59.54   51.59   59.22    77.87   60.54
79       國立政治大學      NaN   7.0   59.29   52.43   53.99    95.12   51.82
80       國立陽明大學      NaN   8.0   58.02   59.87   54.47    62.00   58.04
81       國立中山大學      NaN   9.0   56.78   50.63   51.86    76.77   62.64
82       國立中興大學      NaN  10.0   56.76   47.82   56.88    69.87   64.22
83       國立中央大學      NaN  11.0   56.61   53.74   54.77    60.39   63.83
84         長庚大學      NaN  12.0   56.47   56.02   55.96    62.69   52.53
85       中國醫藥大學      NaN  13.0   55.91   53.97   55.96    65.79   50.45
86     國立臺灣科技大學      NaN  14.0   55.51   47.42   50.13    80.00   62.45
87     國立臺北科技大學      NaN  15.0   54.02   46.64   52.62    67.62   60.89
88       高雄醫學大學      NaN  16.0   53.52   49.56   53.43    65.86   50.66
89         元智大學      NaN  17.0   49.75   44.99   44.89    73.91   48.02
90         淡江大學      NaN  18.0   48.18   27.49   48.40    97.09   47.03
91         世新大學      NaN  19.0   48.08   43.73   44.97    70.62   42.96
92         逢甲大學      NaN  20.0   46.53   25.79   49.93    86.63   46.90
93         輔仁大學      NaN  21.0   45.98   29.40   49.67    79.06   43.00
94       國立中正大學      NaN  22.0   45.74   49.50   29.31    64.68   56.36
95         東海大學      NaN  23.0   45.26   26.21   48.91    79.99   46.46
96     國立高雄科技大學      NaN  24.0   45.19   25.35   49.24    64.14   63.12
97     國立臺灣海洋大學      NaN  25.0   44.80   25.67   49.42    66.58   56.91
98         中原大學      NaN  26.0   44.74   26.11   48.45    74.46   49.84
99       國立臺北大學      NaN  27.0   44.63   29.49   47.96    67.08   49.74
100        亞洲大學      NaN  28.0   44.27   48.38   26.45    76.93   43.58
101      中國文化大學      NaN  29.0   44.26   26.48   43.76    78.58   52.59
102    國立雲林科技大學      NaN  30.0   43.72   44.60   27.73    66.14   56.57
103        銘傳大學      NaN  31.0   43.64   26.64   44.49    79.11   45.86
104    國立彰化師範大學      NaN  32.0   43.55   26.42   48.91    60.97   53.58
105    國立屏東科技大學      NaN  33.0   43.49   24.84   46.38    66.61   57.15
106        東吳大學      NaN  34.0   43.34   27.89   47.47    73.46   39.66
107    國立臺中教育大學      NaN  35.0   42.41   45.87   28.48    61.10   48.14
108        實踐大學      NaN  36.0   42.22   25.27   44.31    79.61   39.48
109    國立臺北商業大學      NaN  37.0   41.00   23.08   47.38    59.50   49.45
110    國立臺北教育大學      NaN  38.0   40.93   25.51   47.93    53.29   48.19
111      明新科技大學      NaN  39.0   38.61   21.96   44.02    61.58   41.86
112        真理大學      NaN  40.0   38.19   23.94   43.66    58.20   38.62
113    國立虎尾科技大學      NaN  41.0   38.13   41.98   24.84    46.09   52.19
114      國立東華大學      NaN  43.0   37.04   27.75   28.03    61.66   55.10
115        慈濟大學      NaN  44.0   36.80   27.04   31.48    64.59   44.16
116      臺北市立大學      NaN  45.0   36.41   27.36   29.03    62.61   48.56
117        中華大學      NaN  46.0   36.00   23.32   25.97    78.64   46.39
118        義守大學      NaN  47.0   35.88   24.40   25.62    74.40   48.09
119        靜宜大學      NaN  48.0   35.73   25.20   24.13    80.76   42.31
120      國立宜蘭大學      NaN  49.0   35.72   24.64   28.32    64.13   50.42
121      國立高雄大學      NaN  50.0   35.58   24.27   27.30    67.45   49.43

In [173]:
data_fund = result.groupby(['Name'])['Fund'].sum().reset_index()
data_fund

          Name     Fund
0         Name     Fund
1      一貫道天皇學院      517
2         世新大學    6,016
3     中信金融管理學院      889
4         中原大學   13,558
5       中國文化大學    7,231
6       中國醫藥大學   20,226
7       中山醫學大學    5,874
8         中華大學    4,732
9         亞洲大學    6,370
10        佛光大學    4,842
11        元智大學    8,377
12        南華大學    6,012
13      台灣首府大學    1,114
14      國立中央大學   41,546
15      國立中山大學   25,303
16      國立中正大學   16,391
17      國立中興大學   35,202
18      國立交通大學  100,000
19      國立嘉義大學    5,745
20      國立宜蘭大學    5,424
21      國立屏東大學    6,774
22    國立屏東科技大學        0
23    國立彰化師範大學    5,816
24      國立成功大學  110,000
25      國立政治大學   28,579
26    國立暨南國際大學    7,179
27      國立東華大學    5,163
28      國立清華大學  100,000
29      國立聯合大學    4,476
30    國立臺中教育大學    4,547
31    國立臺北商業大學        0
32      國立臺北大學    7,805
33    國立臺北教育大學    5,202
34    國立臺北科技大學        0
35    國立臺北藝術大學    4,818
36      國立臺南大學    4,596
37    國立臺南藝術大學    1,361
38      國立臺東大學    5,007
39      國立臺灣大學  180,000
40    國立臺灣師範大學   20,690
41    國立臺灣海洋大學   13,529
42    國立臺灣科技大學        0
43    國立臺灣藝術大學    3,188
44  國立臺灣體育運動大學    3,019
45    國立虎尾科技大學        0
46      國立金門大學    3,435
47      國立陽明大學   34,190
48    國立雲林科技大學        0
49      國立體育大學    3,996
50      國立高雄大學    4,519
51    國立高雄師範大學    4,074
52    國立高雄科技大學        0
53        大同大學    3,920
54        大葉大學    6,964
55        學校名稱     核定經費
56        實踐大學    6,632
57        康寧大學    1,583
58        慈濟大學    5,375
59      明新科技大學        0
60        明道大學    1,668
61        東吳大學    8,968
62        東海大學   12,358
63      法鼓文理學院      381
64        淡江大學    8,907
65        玄奘大學    3,917
66        真理大學    2,154
67   稻江科技暨管理學院      202
68        義守大學    6,854
69      臺北市立大學    4,440
70      臺北醫學大學   26,740
71        華梵大學    2,887
72        輔仁大學    8,290
73        逢甲大學   14,820
74        銘傳大學    7,368
75        長庚大學   16,914
76        長榮大學    5,397
77        開南大學    1,871
78        靜宜大學    8,672
79       馬偕醫學院    4,306
80      高雄醫學大學   10,052

109年各大學學生人數：

In [195]:
student_109 = pd.read_csv('109 student.csv')

學術成就：

In [175]:
academic_achivement = pd.read_csv('academic achivement.csv')

In [176]:
print("原始欄位名稱：", academic_achivement.columns)

原始欄位名稱： Index(['排名', '學校名稱', '總分', '獲獎/榮譽', '英文論文數', '師均英文', '中文論文數', '師均中文'], dtype='object')

In [177]:
new_column_names = ['Rank', 'Name', 'Score', 'Awards/Honored Students', 'Number of English Papers', 'Number of English Papers/Teachers', 'Number of Chinese Papers', 'Number of Chinese Papers/Teachers']
academic_achivement.columns = new_column_names
academic_achivement.to_csv('All University Fund.csv', index=False)

In [178]:
academic_achivement=academic_achivement.drop(0)

In [179]:
academic_achivement

,Rank,Name,Score,Awards/Honored Students,Number of English Papers,Number of English Papers/Teachers,Number of Chinese Papers,Number of Chinese Papers/Teachers
1,1.0,國立臺灣大學,100.00,100,100.00,77.11,100.00,70.98
2,2.0,國立清華大學,64.14,60.99,55.79,68.39,55.74,62.99
3,3.0,國立陽明大學,59.87,36.61,58.92,100,58.53,100
4,4.0,國立成功大學,59.69,48.31,65.97,67.62,64.11,59.46
5,5.0,長庚大學,56.02,40.51,64.20,92.75,48.26,59.78
6,6.0,國立臺灣師範大學,55.28,39.54,45.70,55.41,75.18,89.26
7,7.0,國立交通大學,54.92,48.31,55.21,70.35,46.27,51.49
8,8.0,中國醫藥大學,53.97,35.63,61.12,95.01,48.86,65.85
9,9.0,國立中央大學,53.74,43.44,51.68,68.15,52.05,64.26
10,10.0,國立政治大學,52.43,37.59,40.62,49.77,70.79,91.76
11,11.0,臺北醫學大學,51.59,37.59,57.59,79.24,47.96,57.98
12,12.0,國立中山大學,50.63,37.59,48.86,67.92,51.25,69.53
13,13.0,高雄醫學大學,49.56,36.61,53.33,74.81,46.37,57.13
14,14.0,國立中正大學,49.50,36.61,41.83,53.46,57.63,81.34
15,15.0,亞洲大學,48.38,35.63,46.09,68.33,46.67,67.99
16,16.0,國立中興大學,47.82,37.59,49.77,61.73,48.16,53.44
17,17.0,國立臺灣科技大學,47.42,37.59,47.92,67.01,43.38,52.88
18,18.0,國立臺北科技大學,46.64,35.63,47.15,66.68,44.07,55.79
19,19.0,國立臺中教育大學,45.87,35.63,38.07,48.22,43.77,82.13
20,20.0,元智大學,44.99,34.66,41.73,59.39,42.98,62.49

教學環境：

In [180]:
teaching_environment = pd.read_csv('teaching environment.csv')

In [181]:
print("原始欄位名稱：", teaching_environment.columns)

原始欄位名稱： Index(['排名', '學校名稱', '總分', '傑出校友', '學校總經費', '學生平均', '註冊率', '生師比'], dtype='object')

In [182]:
new_column_names = ['Rank', 'Name', 'Score', 'Distinguished Alumni', 'Total Fund', 'Total Fund/students', 'Registration Rate', 'Students/Teachers']
teaching_environment.columns = new_column_names
teaching_environment.to_csv('All University Fund.csv', index=False)

In [183]:
teaching_environment=teaching_environment.drop(0)

In [184]:
teaching_environment

,Rank,Name,Score,Distinguished Alumni,Total Fund,Total Fund/students,Registration Rate,Students/Teachers
1,1.0,國立臺灣大學,100.00,100,82.98,87.06,88.38,100.00
2,2.0,國立成功大學,66.65,67.44,72.78,86.68,87.34,53.08
3,3.0,國立交通大學,62.16,55.64,72.71,80.41,91.86,49.05
4,4.0,國立清華大學,59.49,53.87,65.23,77.31,92.88,46.85
5,5.0,臺北醫學大學,59.22,49.74,99.85,100,94.60,35.85
6,6.0,國立中興大學,56.88,51.23,64.81,84.03,89.27,42.45
7,7.0,國立臺灣師範大學,56.36,54.4,67.95,83.59,87.75,40.25
8,8.0,中國醫藥大學,55.96,51.57,94.23,86.36,84.89,34.76
9,9.0,長庚大學,55.96,52.46,100.00,94.64,68.08,34.39
10,10.0,國立中央大學,54.77,51.32,71.90,83.72,86.50,37.69
11,11.0,國立陽明大學,54.47,42.21,88.74,97.5,70.67,36.22
12,12.0,國立政治大學,53.99,47.81,57.77,73.64,89.26,41.72
13,13.0,高雄醫學大學,53.43,45.03,78.73,94.32,63.94,37.32
14,14.0,國立臺北科技大學,52.62,43.24,55.54,73.67,80.72,42.45
15,15.0,國立中山大學,51.86,45.87,68.91,82.87,82.98,35.49
16,16.0,國立臺灣科技大學,50.13,44.1,60.51,68.89,94.35,35.49
17,17.0,逢甲大學,49.93,49.69,55.16,51.63,83.13,39.52
18,18.0,輔仁大學,49.67,50.76,52.22,50.71,78.52,40.25
19,19.0,國立臺灣海洋大學,49.42,41.7,61.39,79.49,77.32,35.49
20,20.0,國立高雄科技大學,49.24,50.93,52.09,61.17,91.86,35.49

國際化程度：

In [185]:
degree_of_internationalization = pd.read_csv('degree of internationalization.csv')

In [186]:
print("原始欄位名稱：", degree_of_internationalization.columns)

原始欄位名稱： Index(['排名', '學校名稱', '總分', '本國學生', '跨國學位', '國際學生', '國際教師', '國際合著'], dtype='object')

In [187]:
new_column_names = ['Rank', 'Name', 'Score', 'Numbers of Exchanging Domestic Students', 'Numbers of Cooperating Transnational Degrees Schools', 'International Students Rate', 'International Teachers', 'Proportion of International Co-Authored Papers']
degree_of_internationalization.columns = new_column_names
degree_of_internationalization.to_csv('All University Fund.csv', index=False)

In [188]:
degree_of_internationalization=degree_of_internationalization.drop(0)

In [189]:
degree_of_internationalization

,Rank,Name,Score,Numbers of Exchanging Domestic Students,Numbers of Cooperating Transnational Degrees Schools,International Students Rate,International Teachers,Proportion of International Co-Authored Papers
1,1.0,國立臺灣大學,100.00,77.97,82.26,61.24,66.71,100
2,2.0,淡江大學,97.09,83.77,77.89,76.6,76.42,83.09
3,3.0,國立政治大學,95.12,81.73,85.41,76.88,77.8,76.37
4,4.0,國立交通大學,87.87,75.73,80.62,75.08,100,56.84
5,5.0,逢甲大學,86.63,77.37,77.13,61.41,100,60.55
6,6.0,國立清華大學,84.43,85.51,79.41,69.4,86.13,54.51
7,7.0,文藻外語大學,81.07,97.66,60.54,100,50.06,51.65
8,8.0,靜宜大學,80.76,76.32,67.52,80.21,62.54,59.34
9,9.0,國立臺灣師範大學,80.56,74.29,85.01,62.36,76.42,55.31
10,10.0,國立臺灣科技大學,80.00,72.42,100,75.71,61.16,50.16
11,11.0,東海大學,79.99,72.76,73.02,85.3,69.48,52.17
12,12.0,實踐大學,79.61,95.97,67.09,78.78,70.87,47.3
13,13.0,銘傳大學,79.11,65.65,91.05,73.42,65.32,53.14
14,14.0,輔仁大學,79.06,58.71,68.55,73.46,73.64,60.06
15,15.0,中華大學,78.64,83.11,64.42,53.17,75.03,59.74
16,16.0,中國文化大學,78.58,66.61,69.21,65.38,72.25,59.9
17,17.0,臺北醫學大學,77.87,65.98,89.88,51.66,66.71,59.3
18,18.0,國立成功大學,77.24,67.38,80.43,54.25,87.51,51.33
19,19.0,亞洲大學,76.93,78.04,62.56,64.74,66.71,57.21
20,20.0,國立中山大學,76.77,77.26,70.12,80.1,59.77,50.93

產學績效：

In [190]:
industry_university_performance = pd.read_csv('industry-university performance.csv')

In [191]:
print("原始欄位名稱：", industry_university_performance.columns)

原始欄位名稱： Index(['排名', '學校名稱', '總分', '推廣及', '師均推廣', '智慧財產權', '美國核准', '臺灣核准'], dtype='object')

In [192]:
new_column_names = ['Rank', 'Name', 'Score', 'Promotion and Industry-University Income', 'Promotion and Industry-University Income/Teachers', 'Total Amount of Derivative Use of Intellectual Property Rights', 'Number of Invention Patents Approved by USA', 'Number of Invention Patents Approved by Taiwan']
industry_university_performance.columns = new_column_names
industry_university_performance.to_csv('All University Fund.csv', index=False)

In [193]:
industry_university_performance=industry_university_performance.drop(0)

In [194]:
industry_university_performance

,Rank,Name,Score,Promotion and Industry-University Income,Promotion and Industry-University Income/Teachers,Total Amount of Derivative Use of Intellectual Property Rights,Number of Invention Patents Approved by USA,Number of Invention Patents Approved by Taiwan
1,1.0,國立臺灣大學,100.00,100,100,100,84.17,80.39
2,2.0,國立清華大學,77.98,57.45,91.22,77.17,100,100
3,3.0,國立交通大學,75.95,59.09,98.8,74.33,75.23,71.06
4,4.0,國立成功大學,74.84,69.97,91.3,57.22,60.78,90.66
5,5.0,國立臺灣師範大學,64.95,57.95,91.39,46.37,51.14,63.59
6,6.0,國立中興大學,64.22,55.02,88.88,54.03,42.88,64.05
7,7.0,國立中央大學,63.83,55.1,95.9,44.64,50.45,54.25
8,8.0,國立高雄科技大學,63.12,54.74,84.69,51.07,44.26,72.92
9,9.0,國立中山大學,62.64,50.07,91.46,48.94,49.08,70.59
10,10.0,國立臺灣科技大學,62.45,48.45,88.38,53.11,53.89,69.19
11,11.0,國立臺北科技大學,60.89,47.65,88.04,52.71,44.95,64.05
12,12.0,臺北醫學大學,60.54,41.29,65.1,93.8,42.88,46.78
13,13.0,國立陽明大學,58.04,46.7,89.59,43.84,45.64,50.51
14,14.0,國立屏東科技大學,57.15,45.59,85.39,45.9,41.51,57.52
15,15.0,國立臺灣海洋大學,56.91,46.23,87.26,44.74,40.13,48.65
16,16.0,國立雲林科技大學,56.57,45.73,85.88,44.37,40.13,52.85
17,17.0,國立中正大學,56.36,47.19,82.05,44.51,44.26,49.58
18,18.0,國立東華大學,55.10,46.13,82.84,42.53,40.13,45.85
19,19.0,國立暨南國際大學,53.79,41.98,81.8,42.52,44.26,50.51
20,20.0,國立彰化師範大學,53.58,43.38,80.08,42.82,40.13,49.11